### ISSUE TITLE
Enviroment variables for account details

### ISSUE THREAD

**Issue by einarf** [Budabot/Tyrbot#69]
A suggestion:

When running Tyrbot in docker it's nice to save a compose setup and config in a git repository. Some are weary saving account details in git, so an improvement could be the following:

Support the following enviroment variables:

```
TYRBOT_USERNAME
TYRBOT_PASSWORD
TYRBOT_CHARACTER
TYRBOT_SUPERADMIN
```

This would replace the coresponding values in the `config.hjson`. This way the bot operators can keep and docker `env` file outside git.

account.env (not in version control)
```bash
TYRBOT_USERNAME=myaouser
TYRBOT_PASSWORD=aopassword
TYRBOT_CHARACTER=mrbot
TYRBOT_SUPERADMIN=theboss
```

docker-compose.yaml
```yaml
bot:
    build: mybot
    env_file:
        - account.env
```

**Comment by bigwheels16** [comment]
What is the benefit of putting account details in an `account.env` file compared to putting them in the `config.hjson` file and exposing with a volume?

```
bot:
    build: mybot
    volumes:
        - ./config.hjson:/app/conf/config.hjson
```
